version: "3.8"
services:
  # Symfony apache project container
  www:
    build: docker/php
    container_name: symfony_app
    ports:
      - "8008:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - symfony_app

  # Mysql database container
  database:
    image: mysql:8
    container_name: database
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/run.sh:/stack/localdb/run.sh:rw
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: verySecretPassword
    networks:
      - symfony_app

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - symfony_app



networks:
  symfony_app:
    driver: bridge

volumes:
  db-data: